org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
neo_version_range=[21.1.235
loader_version_range=[4,)

# Mod
mod_id=mared
mod_name=MaRed
mod_license=All Rights Reserved
mod_version=0.3.5
mod_group_id=com.fixmer.mared
mod_authors=FixMeR
mod_description=Powerful script engine for Minecraft