org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.235
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mod
mod_id=mared
mod_name=Mared
mod_license=MIT
mod_version=0.3.1
mod_group_id=com.fixmer.mared
mod_authors=fixmer
mod_description=Mared — мощный скриптовый движок для Minecraft с гибридным синтаксисом, биндами, событиями и редактором в игре.