modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/fixmer/mared/issues"

[[mods]]
modId = "mared"
version = "${mod_version}"
displayName = "Mared"
authors = "fixmer"
description = '''
Mared — мощный скриптовый движок для Minecraft с гибридным синтаксисом,
биндами на клавиши, событиями, persistent-скриптами и редактором в игре.
'''
logoFile = "mared_logo.png"

[[dependencies.mared]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.235,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mared]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mared.mixins.json"