package com.fixmer.mared;
import com.fixmer.genesis.technology.runtime.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class PortableRuntimeIntegrationTest {
 private static final ExecutionLimits LIMITS=new ExecutionLimits(2,100,8,1_000_000_000L);
 @Test void budgetAndNormalCompletion(){int[] hits={0};FrameExecutor.Instruction hit=e->hits[0]++;var scope=new ExecutionScope();var e=new FrameExecutor(List.of(hit,hit,hit),LIMITS,scope);e.tick();assertEquals(2,hits[0]);assertFalse(e.isFinished());e.tick();assertEquals(3,hits[0]);assertTrue(e.isFinished());assertEquals(0,scope.snapshot().resources());}
 @Test void singleStepDoesNotRunWholeTick(){int[] hits={0};FrameExecutor.Instruction hit=e->hits[0]++;var e=new FrameExecutor(List.of(hit,hit),LIMITS,null);e.pauseFromDebugger();e.stepOverDebugger();assertEquals(1,hits[0]);assertTrue(e.snapshot().paused());e.tick();assertEquals(1,hits[0]);e.resumeFromDebugger();e.tick();assertTrue(e.isFinished());}
 @Test void pauseAndRetry(){int[] hits={0};var e=new FrameExecutor(List.of(x->{hits[0]++;if(hits[0]<2)x.retryCurrentInstruction();else x.completeRetry();},x->hits[0]+=10),new ExecutionLimits(1,100,8,1_000_000_000L),null);e.tick();assertEquals(1,hits[0]);e.tick();assertEquals(2,hits[0]);e.tick();assertEquals(12,hits[0]);assertTrue(e.isFinished());var wait=new FrameExecutor(List.of(new FrameExecutor.Instruction(){public void execute(FrameExecutor x){}public int getDelayTicks(){return 2;}},x->hits[0]++),LIMITS,null);wait.tick();assertTrue(wait.snapshot().waiting());wait.tick();wait.tick();assertEquals(12,hits[0]);wait.tick();assertEquals(13,hits[0]);}
 @Test void cleanupRunsOnOwnerTick(){AtomicInteger cleaned=new AtomicInteger();var scope=new ExecutionScope();var e=new FrameExecutor(List.of(x->x.pauseCurrent(100)),LIMITS,scope);e.pushLoopInstructions(List.of(x->x.pauseCurrent(100)),new FrameExecutor.LoopOwner(){public boolean onBodyFinished(FrameExecutor ex,FrameExecutor.Frame f){return false;}public String describe(){return "test";}public void onDiscard(){cleaned.incrementAndGet();}});e.tick();e.pauseFromDebugger();scope.close();assertEquals(0,cleaned.get());assertEquals(1,scope.snapshot().resources());e.tick();assertEquals(1,cleaned.get());assertEquals(0,scope.snapshot().resources());assertTrue(e.isFinished());}
 @Test void failureCancelsSiblingResources(){var scope=new ExecutionScope();AtomicInteger closed=new AtomicInteger();scope.own(ExecutionScope.Kind.EVENT,closed::incrementAndGet);var e=new FrameExecutor(List.of(x->{throw new IllegalStateException("bad host");}),LIMITS,scope);e.tick();assertTrue(e.isFinished());assertNotNull(e.failure());assertTrue(scope.cancelled());assertEquals(1,closed.get());assertEquals(0,scope.snapshot().resources());}
 @Test void stackLimitIsEnforced(){var e=new FrameExecutor(List.of(x->x.pushInstructions(List.of(y->{}))),new ExecutionLimits(1,10,1,1_000_000_000L),null);e.tick();assertNotNull(e.failure());assertTrue(e.isFinished());}
 @Test void actionClaimsAreIndependent(){var a=new OwnedActions<String,String>(4);var one=new ExecutionScope();var two=new ExecutionScope();a.press(one,"forward");a.press(one,"forward");a.press(two,"forward");assertEquals(1,one.snapshot().resources());one.close();assertTrue(a.activeKeys().contains("forward"));assertTrue(a.pressed(two,"forward"));a.release(two,"forward");assertTrue(a.activeKeys().isEmpty());assertEquals(0,two.snapshot().resources());a.press(null,"left");a.stop(one);assertTrue(a.activeKeys().contains("left"));a.stopAll();assertTrue(a.activeKeys().isEmpty());}
 @Test void pendingActionsAreBoundedAndCancelled(){var a=new OwnedActions<String,Integer>(2);var one=new ExecutionScope();var two=new ExecutionScope();a.enqueue(one,1);a.enqueue(two,2);assertThrows(IllegalStateException.class,()->a.enqueue(two,3));one.close();var effects=new ArrayList<Integer>();a.drain(1,effects::add);assertEquals(List.of(2),effects);assertEquals(0,two.snapshot().resources());a.enqueue(two,4);a.drain(1,x->{throw new IllegalArgumentException("effect");});assertTrue(two.cancelled());assertNotNull(two.snapshot().failure());assertEquals(0,a.pendingCount());a.enqueue(two,5);assertEquals(0,a.pendingCount());}
 @Test void racingActionsCannotEscapeScope()throws Exception{for(int i=0;i<100;i++){var scope=new ExecutionScope();var a=new OwnedActions<String,Integer>(4);var start=new CountDownLatch(1);AtomicReference<Throwable> error=new AtomicReference<>();Thread thread=new Thread(()->{try{start.await();a.press(scope,"forward");a.enqueue(scope,1);}catch(Throwable e){error.set(e);}});thread.start();start.countDown();scope.close();thread.join();assertNull(error.get());assertTrue(a.activeKeys().isEmpty());assertEquals(0,a.pendingCount());assertEquals(0,scope.snapshot().resources());}}
}
